spring:
  datasource:
    url: jdbc:h2:mem:db_test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  data:
    redis:
      host: localhost
      port: 6379
custom:
  frontendBaseUrl: http://localhost:3000